Theming and UI rework
Volgograd-Power-Engineering-College/vpec pull request #29
Opened 2022-12-19 22:15 UTC by lazurit11

### Fixes:
* Fixed wrong system navigation bar colors while modal sheet is opened 

### Changes:
* Substitute shadows with faint outline
* Slightly change app palette
* Set body text size to standard 16pt
* Make system navigation bar transparent on Android 10+
* Make buttons and their labels bigger
* Change bottom modal sheet style
* Rework announcements editor UI
* Change floating action button style

### Internal changes:
* Introduce ColorPalette extension to simplify painting items and make code more readable
* Shorten theme color queries by using extension on BuildContext

2022-12-23 14:38 UTC, Tembeon requested changes
В целом отлично, но пройдись по комментам. main бы обязательно поменять, не сильно хочется его загромождать методами

2022-12-23 14:38 UTC, Tembeon commented on lib/main.dart
> +
Почему бы не вынести эти строчки изменения хрома в отдельный метод в том же ThemeHelper. Можно даже в метод `initSdkVer`, только переименовать его во что-то другое

2022-12-23 14:38 UTC, Tembeon commented on lib/screens/announcements/editor/editor_ui.dart
> +class TitleEditorField extends StatefulWidget {
у тебя два одиннаковых инпут виджета, и везде ты дублируешь переменные. Лучше вынеси  такой текст инпут в отдельный виджет и юзай его внутри этих классов (TitleEditorField & BodyEditorField)

2022-12-23 14:38 UTC, Tembeon commented on lib/screens/announcements/editor/editor_ui.dart
> +class TitleEditorField extends StatefulWidget {
вообще, необходимо стараться переиспользовать код, а не дублировать его

2022-12-23 14:38 UTC, Tembeon commented on lib/screens/announcements/editor/editor_ui.dart
> +              String field =
если переменные нигде не изменяются после создания, то добавь к ним final

2022-12-23 14:38 UTC, Tembeon commented on lib/screens/teachers/teachers_ui.dart
> +        const SizedBox(height: 10),
вообще, можно использовать Wrap для этого, чтобы не писать везде одинаковые отступы между объектами. Параметр spacing/runSpacing

2022-12-23 14:38 UTC, Tembeon commented on lib/utils/theme_helper.dart
> +  static Future<void> initSdkVer() async {
вообще не особо понятно, зачем инфморация о технической части ОС собирается в классе, отвечающий за темы. Либо вынеси это в отдельный файл, либо обрати внимание на комментарий к `main`. Я бы, наверное, все же переименовал метод во что-то другое, а переменную `_sdkVer` перевел бы во что-то типа `bool androidNavigationBarStylingSupports`

2022-12-23 14:38 UTC, Tembeon commented on lib/utils/theme_helper.dart
> +    required ColoringMode mode,
судя по тому, что ты чаще всего (90% случаев) используешь `ColoringMode.byCurrentTheme`, предлагаю добавить этому параметру значение по умолчанию: `ColoringMode mode = ColoringMode.byCurrentTheme`

2022-12-23 15:46 UTC, lazurit11 commented on lib/utils/theme_helper.dart
> +  static Future<void> initSdkVer() async {
не согласен насчет перевода в bool, но в отдельный класс или файл перенести можно, и где либо переиспользовать, например в фиксе сертификатов для 7 андроида, или в будущем. А перевод в бул даже не укоротит проверку

2022-12-24 19:16 UTC, lazurit11 commented on lib/screens/teachers/teachers_ui.dart
> +        const SizedBox(height: 10),
это не работает, так как `InputDecorator` нельзя помещать в unconstrained виджет

2022-12-24 19:52 UTC, lazurit11 commented on lib/screens/announcements/editor/editor_ui.dart
> +class TitleEditorField extends StatefulWidget {
параметры TextField напрямую обращаются к переменным стейта, совместно с другими виджетами в TitleEditorField или BodyEditorField. Вынос TextField (имхо) не стоит работы.

2022-12-24 20:21 UTC, lazurit11 commented on lib/screens/announcements/editor/editor_ui.dart
> +class TitleEditorField extends StatefulWidget {
не стоит того

2022-12-24 20:31 UTC, Tembeon commented on lib/utils/utils.dart
>      }
В принципе можно было бы сделать даже отдельный класс, который хранит всю инфу об устройстве и инициализировать его в main, чтобы из него дергать разные методы для получения информации. В текущем случае это не является востребованным, ибо мы почти не читаем информацию об устройстве

2022-12-24 20:31 UTC, Tembeon approved these changes
LGTM

2022-12-24 20:34 UTC, merged